__author__ = 'Michael Trotter (trotsky@gwu.edu)'

text = "wkhvkdgrzriwkhprrqvzhswdfurvvwkhjorehiurpkrqjnrqjwrwkhwhadvsdqkdqgohdvduduhdqqxoduvroduhfolsvhehjdqprqgdbpruqlqjlqdvlddqgwudyhuvhgwkhsdflilfwkhvxqdsshduhgdvdwklqulqjehklqgwkhprrqwrshrsohlqdqduurzsdwkdorqjwkhfhqwhuriwkhwudfnzklfkehjdqlqvrxwkhuqfklqdkhdybforxgvrevfxuhgwkhylhzlqkrqjnrqjexwuhvlghqwvriwrnbrdqgrwkhuflwlhvzhuhdeohwrjhwdvshfwdfxoduylhziruderxwirxuplqxwhvdurxqgvhyhqwkluwbwzrdpprqgdbvlawkluwbwzrsphwvxqgdbhyhqwvzhuhkhogdwvfkrrovdqgpxvhxpvlqmdsdqzklohpdqbpruhshrsohwrrnlqwkhxqxvxdodvwurqrplfdohyhqwdwkrphrurqvwuhhwfruqhuvdiwhuzklcclqjdfurvvwkhsdflilfwkhvkdgrzhphujhgryhuqruwkhuqfdoliruqlddqgvrxwkhuqruhjrqzkhuhwkrxvdqgvrishrsohdwwhqghgsduwlhvwrzdwfkwkhhyhqwwkhiluvwwrdsshdulqwkhxqlwhgvwdwhvvlqfhqlqhwhhqqlqhwbirxuhashuwvzduqhgwkdwkrshixoylhzhuvvkrxogqrwshhuxsdwwkhvnbzlwkrxwvshfldoylhzlqjhtxlsphqwvlqfhorrnlqjdwwkhvxqzlwkwkhqdnhghbhfdqfdxvheolqgqhvvghuhnudovwrqdsurihvvlrqdoskrwrjudskhuvdlgkhxvhgdzhoglqjilowhuwrfdswxuhdgluhfwylhzrihfolsvhlqwkhirrwkloovderyhruryloohfdoliruqldkhvkduhgwkhskrwrrqfqqluhsruwqrwlqjwkhudwkhuvolpvzdwkriwkhjorehzkrfrxogvhhwkhlpsdfwriwkhhfolsvhudovwrqvdlgkhzdqwhgwrhqdeohwkhuhvwriwkhzruogwrvhhkrzfohdulworrnhgwrwkrvhrixvzkrzhuhiruwxqdwhhqrxjkwrvhhlwwkhvolyhurivxqvklqhwkhqwudyhohgvrxwkhdvwdfurvvfhqwudoqhydgdvrxwkhuqxwdkdqgqruwkhuqdulcrqddqgwkhqqhzphalfrlwsdvvhgryhudoextxhutxhqhzphalfrderxwvhyhqwkluwbirxuspqlqhwkluwbirxusphwehiruhshwhulqjrxwhdvwrioxeerfnwhadvdffruglqjwrqdvd"
total = float(len(text))
freq_table = {}

for c in text:
    if c in freq_table:
        freq_table[c] += 1
    else:
        freq_table[c] = 1

for key in sorted(freq_table, key=lambda key: key):
    print("%s: %s" % (key, str(round(freq_table[key] / total * 100, 2))))